### ISSUE TITLE
update for the recent css spec change?

### ISSUE THREAD

**Issue by taylorchu** [gorilla/css#1]
i think you use the version which dated from 2003. 

http://www.w3.org/TR/2003/WD-css3-syntax-20030813/

Well, a lot happen in a decade.

**Comment by pravj** [comment]
Nope, you're thinking wrong.

It uses the latest specifications. Check [here](https://github.com/gorilla/css/blob/master/scanner/doc.go#L8-L10).

```go
It follows the CSS3 specification located at:
	http://www.w3.org/TR/css3-syntax/
```

**Comment by kisielk** [comment]
Is there something missing that needs to be implemented? Please be more specific.
